module.exports.names = [
  "Sunset Spot",
  "Shadow Haven",
  "Fast Lane Refuge",
  "Crimson Curve",
  "Golden Gear Bay",
  "Skyline Stop",
  "Steel Stead",
  "Ridgeback Rest",
  "Velocity Vault",
  "Copper Corner",
  "Starlight Spot",
  "The Pivot Pad",
  "Turbo Terrace",
  "Civic Circle",
  "Travelers Terminal",
  "Meadowline Park",
  "Gridlock Escape",
  "Zen Zone",
  "Beacon Bay",
  "Driver’s Den",
];
